### ISSUE TITLE
about FBMS dataset

### ISSUE THREAD

**Issue by Castile** [tfzhou/MATNet#10]
Hi， would you provide your FBMS dataset? because it contains multi-object, so I want to know what operations you use in FBMS or do some others process. It would be nice to provide the test data that you are using. THX!!!

**Comment by tfzhou** [comment]
Hi, @Castile. Our MATNet focuses on segmenting primary object(s) in videos. FBMS is used similarly with DAVIS and Youtube-Objects to verify the performance of our method towards this goal. We use the standard test data in FBMS. You can find it at: [https://lmb.informatik.uni-freiburg.de/resources/datasets/moseg.en.html](https://lmb.informatik.uni-freiburg.de/resources/datasets/moseg.en.html)
