### ISSUE TITLE
Youtube-object

### ISSUE THREAD

**Issue by yangshushuaige** [tfzhou/MATNet#11]
您好，对于Youtube-object，您使用的光流是基于高分辨的检测数据集的image计算的吗，因为您给出的Result的分辨率是与检测数据集分辨率对应的。（与使用Youtube-Object Mask的数据集中低分辨率的image是否有差异，我产生的光流基本上都是噪声）另外您的光流计算是基于检测数据集（00001-00002）计算光流还是Mask数据集（00001-00011）计算光流？
我用基于Davis的test代码测试Davis 16结果与论文吻合（忽略第一帧和最后一帧），但是在测试Youtube-object数据集上存在极大的差异，您是否方便公开一下测试代码？（比如car0001的真值中有00201，但是因为00201没有光流，所以您给出的结果没有第201帧的结果）
另外，还有一些私人问题给您发了邮件，期待着您的回复。

**Comment by tfzhou** [comment]
Hi, I think the dataset we have used is different. This is the reason why you cannot reproduce the scores on youtube-objects. The masks I provided has the same resolution with my input images/ground-truths. For the last frame issue, I follow a standard convention to ignore them.

**Comment by yangshushuaige** [comment]
您是否可以分享一下正确数据集的链接吗？这是我现在使用的数据集：http://vision.cs.utexas.edu/projects/videoseg/，其image的分辨率都是640*360或者450*360之类的，困惑了我很久，感谢您的帮助。

**Comment by lartpang** [comment]
@tfzhou 您使用的是这个数据集么 http://vision.cs.utexas.edu/projects/videoseg/ 
我发现这里的数据中的标注数量非常少，而且还都是低分辨率的，和您给的结果不太一样 😃  。
我想和您的结果进行比较一下。所以还需要麻烦您提供一下您使用的数据的下载链接。非常感谢！
