### ISSUE TITLE
Why are my results much terrible than yours?

### ISSUE THREAD

**Issue by Starboy-at-earth** [tfzhou/MATNet#12]
Dear author:
        I have used your provided code to train the model to study UVOS. Slightly different from yours, my running deploys a more advanced optical net named RAFT to generate flow graphs. However, my Jaccard is 0.762, much lower than your 0.8-odd.  Other than RAFT, my running configration is totally cosistent with your published. Could you please tell me what is wrong with my settings? Your reply is desired.

**Comment by Starboy-at-earth** [comment]
I have reproduced your results. Your job is much more solid than others and the code is very compact and beautiful. It is regretful not to communicate with you by Email. Thank you very much.

**Comment by tfzhou** [comment]
Hi, @Starboy-at-earth Sorry for that I did not notice your issue and glad to see you got the desired results. Please feel free to reach me if you met other problems.

**Comment by tfzhou** [comment]
By the way @Starboy-at-earth , would you mind to share more information about how you improve the results? Do the preliminary bad results mainly caused by the different flow computation algorithm?
