### ISSUE TITLE
hi,i have a question.I want to know how many epoch you trained in DAVIS16 ? Thank you !

### ISSUE THREAD

**Issue by Selenating** [tfzhou/MATNet#14]

**Comment by Selenating** [comment]
and how you use the optical flow to train?you use the visual RGB optical flow image（3 channels） or optical flow truth value（2 channels）？

**Comment by tfzhou** [comment]
Hi, all the implemention details have been revealed in the released codes which is expected to reproduce our results. Please see the codes. For your problem, we train 25 epochs in total and employ 3-channel optical flow images. Thanks.
