### ISSUE TITLE
您好，您主页上paper的连接好像打不开

### ISSUE THREAD

**Issue by wangbo-zhao** [tfzhou/MATNet#2]

**Comment by tfzhou** [comment]
@wangbo-zhao I will submit to Arxiv next week. Will let you know then.

**Comment by wangbo-zhao** [comment]
Thank you ------------------ 原始邮件 ------------------
发件人: "Tianfei Zhou"<notifications@github.com>
发送时间: 2020年2月27日(星期四) 下午3:54
收件人: "tfzhou/MATNet"<MATNet@noreply.github.com>;
抄送: "wangbo-zhao"<448549537@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [tfzhou/MATNet] 您好，您主页上paper的连接好像打不开 (#2)



@wangbo-zhao I will submit to Arxiv next week. Will let you know then.
 
&mdash;

**Comment by tfzhou** [comment]
@wangbo-zhao Paper link updated in the repo

**Comment by wangbo-zhao** [comment]
thanks
