### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by MSiam** [tfzhou/MATNet#23]
Hello thanks for your code

   When I try to train MATNet after performing all the steps for dataset preparation. I still find the code is looking for these two json files can you please share them?
"train-train-meta.json"
"train-val-meta.json"

Thanks

**Comment by tfzhou** [comment]
Hi, these files should be provided by the Youtube-VOS dataset.

**Comment by MSiam** [comment]
I didnt find them with YoutubeVOS 2018 dataset

I did find them however in RVOS repo they do provide https://github.com/imatge-upc/rvos
I am assuming you followed the setup from AGS which followed these I am guessing?

Cause they are the "train/val splits within the train" split. YoutubeVOS provides the train and val splits, without redividing train split again.

**Comment by tfzhou** [comment]
I am sorry that I cannot remember the details, but you can change the dataloader to fit the annotations. I did not follow the setting in AGS, but you can also refer to its setting.

**Comment by MSiam** [comment]
thanks for your reply I will. Just small question in the paper you do mention "In total, we have 14K training sam-
ples, basically matching AGS (Wang et al. 2019b)" so it is safe to assume you are following AGS training setup I mean and what data you are using so I can refer later to that?

**Comment by tfzhou** [comment]
Yes. Both MATNet and AGS use about 14K data for training. However, the training datasets they used are different. For MATNet,  youtubevos and davis are used for training.

**Comment by MSiam** [comment]
I see thanks for your help
