### ISSUE TITLE
光流图是否在DAVIS数据集上训练过？

### ISSUE THREAD

**Issue by huanglf714** [tfzhou/MATNet#28]
你好，我想请问一下，准备数据环节，准备的光流图是直接用pytorch-pwc在其他光流数据集上训练得到的权重预测生成的吗，您有在DAVIS数据集上训练吗，如果有，可不可以提供一下预训练模型呢？

**Comment by tfzhou** [comment]
No, the optical flow model is not fine-tuned on DAVIS. We directly use the off-the-shelf model.
