### ISSUE TITLE
data list

### ISSUE THREAD

**Issue by jiaozizhao** [tfzhou/MATNet#3]
Hi, in your paper, you said you use DAVIS16 with 4K frames and YoutubeVOS with 12K frames. However, I found in DAVIS16 training set, 30 videos only with 2K frames. DAVIS17 training set has about 4K frames. So may I confirm whether you used DAVIS16 or DAVIS17 for traing? And for YoutubeVOS, even sampled every 10 frames, it still has 50K frames. May I know which videos you selected from YoutubeVOS for training, please? Or could you share you training list files to me? Thanks very much.

**Comment by tfzhou** [comment]
1) DAVIS:  I am pretty sure that I use DAVIS-16 for training in all my experiments. It may be wrong about the specific number, which is directly borrowed from a paper. I will update the Arxiv paper regarding this. Thanks.
2) YoutubeVOS: I think you could check the codes for details about the use of YoutubeVOS. However, for your reference, it seems YoutubeVOS only consider 94588 frames in total.

**Comment by jiaozizhao** [comment]
Hi, thanks very much for the reply. May I know you used all the videos in the YoutubeVOS training set, just sampled every 10 frames? I downloaded it and also sampled every 10 frames, the number of frames is much more than 12K.

**Comment by tfzhou** [comment]
Yes, I used all training videos in YoutubeVOS 2018. In my downloaded dataset, the videos have been downsampled every 5 frames. I further downsampled it every 10 frames. I guess that the dataset you have downloaded is not exactly same with mine (may be not downsampled).

**Comment by tfzhou** [comment]
For others' reference: YoutubeVOS has two imagesets with different fps (6fps v.s. 30fps). What MATNet have used is the 6fps version.
