### ISSUE TITLE
run_davis.py and run_youtube.py

### ISSUE THREAD

**Issue by Castile** [tfzhou/MATNet#4]
sorry， I can not find run_davis.py and run_youtube.py two files or projects in your repo. Are you sure you've uploaded it？I have open the '/3rdparty', but I got nothing， I can not click these folders...

**Comment by tfzhou** [comment]
@Castile The scripts have been updated. Thanks.

**Comment by Castile** [comment]
Sorry，I mean the python file.  In pytorch-hed and pytorch-pwc folders. 
In Readme.MD:
" Prepare HED Results
I have provided the pytorch codes to generate HED results for the two datasets (see 3rdparty/pytorch-hed). Please run run_davis.py and run_youtube.py. "

**Comment by tfzhou** [comment]
@Castile I have updated the python scripts. Thanks.
