### ISSUE TITLE
检测目标个数问题

### ISSUE THREAD

**Issue by 124399839** [tfzhou/MATNet#5]
TianFei 您好，请问MATNet网络可是从一个视频中获得多个运动目标的分割吗？谢谢。

**Comment by tfzhou** [comment]
No. MATNet itself only focus on foreground/background segmentation. For multi-object scenarios, we have extended MATNet to multi-object unsupervised segmentation by combining it with object detection and multi-object tracking techniques. The results on DAVIS-2017 validation set can be found in the README.
