### ISSUE TITLE
About Optical Flow

### ISSUE THREAD

**Issue by BruceWang1996** [tfzhou/MATNet#7]
First frame doesn't have optical flow picture, how to deal with this?

**Comment by hailyxu** [comment]
The folder 3rdparty/pytorch-pwc is empty, how did you generate optical flow?

**Comment by tfzhou** [comment]
@hailyxu Please refer to [prepare-optical-flow](https://github.com/tfzhou/MATNet#prepare-optical-flow) in readme for how to run optical flow for your data.

**Comment by tfzhou** [comment]
@BruceWang1996 Actually, we don't have optical flow for the last frame. In our experiments, we simply ignore the last frame, which also follows the standard protocol in DAVIS.

**Comment by hailyxu** [comment]
> @hailyxu Please refer to [prepare-optical-flow](https://github.com/tfzhou/MATNet#prepare-optical-flow) in readme for how to run optical flow for your data.

Thanks for your reply. I have checked the folder 3rdparty/pytorch-pwc, but it's empty, there's no run_davis2017.py in it. I have also go to the original pytorch-pwc repo, but apparently, the code could only produce the optical flow of two frames once.
I would apprecirate it if you could offer some help about optical flow, it's really time comsuming if I go to find other models that produce optical flow results.

**Comment by tfzhou** [comment]
@hailyxu I have updated the optical flow helper scripts in the 3rdparty. Please update it or refer to the commit [https://github.com/tfzhou/MATNet/commit/7a996c1a10b6a991da64d6dc7986de3648ac2cf8](https://github.com/tfzhou/MATNet/commit/7a996c1a10b6a991da64d6dc7986de3648ac2cf8).

**Comment by hailyxu** [comment]
> @hailyxu I have updated the optical flow helper scripts in the 3rdparty. Please update it or refer to the commit [7a996c1](https://github.com/tfzhou/MATNet/commit/7a996c1a10b6a991da64d6dc7986de3648ac2cf8).

Thanks. Good day.
