### ISSUE TITLE
关于多目标训练的问题

### ISSUE THREAD

**Issue by Xiaoqi-Zhao-DLUT** [tfzhou/MATNet#9]
你好，我看您最近更新了在davis17上的结果。 请问，您能公开下关于多目标训练和测试的code吗？ 十分感谢

**Comment by tfzhou** [comment]
@Xiaoqi-Zhao-DLUT Thanks for your interest. Currently, I have no plan to release this part of codes. The code is kind of more complicated, which also rely on external modules (e.g. Mask R-CNN, Re-ID, etc). Besides, we have two different implementations for multi-object segmentation, one for the journal version, and the other for DAVIS-2020 challenge. I have to integrate them together before release. 

By the way, if you have specific problems about multi-object extension, leave message here and I will try to help you out.
